name: ci

on:
  push:
    branches:
      - "main"
      - "develop"
      - "qa"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clean and install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Ensure Angular DevKit is installed
        run: npm install --save-dev @angular-devkit/build-angular

      # Instalar dependencias de Chrome y Chromium para headless mode
      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-xcb1 libxcomposite1 libxrandr2 libxi6 libatk1.0-0 libgtk-3-0 libnss3 libxss1
          sudo apt-get install -y chromium-browser

      - name: Run tests with coverage
        run: npm run test:coverage -- --browsers=ChromiumHeadless --watch=false

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Determine Docker tag
        id: tag
        run: |
          if [ "${GITHUB_REF##*/}" == "main" ]; then
            echo "tag=latest" >> $GITHUB_ENV
          elif [ "${GITHUB_REF##*/}" == "develop" ]; then
            echo "tag=develop" >> $GITHUB_ENV
          elif [ "${GITHUB_REF##*/}" == "qa" ]; then
            echo "tag=qa" >> $GITHUB_ENV
          else
            echo "Error: branch name not recognized"
            exit 1
          fi

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/drivers-front:${{ env.tag }}

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: "beta"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy drivers-front \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/drivers-front:${{ env.tag }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
